#pragma once
#include "carte.h"
#include "repo.h"
#include "service.h"
#include "validator.h"
#include <assert.h>

void testAll();
void test_carte();
void test_adaugare_repo();
void test_actualizare_repo();
void test_stergere_repo();
void test_cmp();
void test_actualizare_service();
void test_stergere_service();
void test_adaugare_service();
void test_gaseste_repo();
void test_cautare_service();
void test_filtrare();
void test_sortare();
void test_adaugare_cos_repo();
void test_golire_cos_repo();
void test_adaugare_cos_service();
void test_golire_cos_service();
void test_generare_cos_service();
void test_get_marime_cos();
void test_undo();
void test_cerinta_noua();
void test_validare_fisier();
void test_export_cos_csv();
void test_export_cos_html();